apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: easybus-data
type: Opaque
data:
  POSTGRES_USER: azh1c2Vy     
  POSTGRES_PASSWORD: azhzdGVzdA== 
  POSTGRES_DB: azhzZGI=           