apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: expedition-secret
  namespace: easybus-services
spec:
  encryptedData:
    DB_PASSWORD: AgBJIYTFVBOinpvUifcSEsY05VJU5fo5PMdJfUHPvxotMX/HbKAX9F5QHApjp7FLROpJWRPqGyIQLR9ohAVFLpzZfeykCgX/4ml1sozUNIex+ItgfgLP55LPv8gUwdxD/6E0lUUasZUazJj6XmbeqM/MPFseZ2D+qsqAU2ymUb9GY1C7O8TAdObIWjAbcWYn2f84SMhH81fdvyFMXviel3bYLjx8nwO+FVtDCO5SBrfpvVurKOQjoPeZ5aAwyla0KGCED5bXSj0wkRZkFPq9TwbU/lOZ2L0ecmx/gTJOvDvZsE8gtW1abz5PbH8eQQIWPJ1n4dh7f5dd+/NK3ROGSKs2ksHn2BjKjKOYXLeCTRgsca/vLFsDURq0eOo8FJ2Ngg7/KMh2TBrH7xmZzmm41ij2mvTDoSCQV2vtfJ/3sNBn1seUIMF0APfc7rbruug4EiE8MULapYREZpLws7WUoBrsgHYbFFtHM5rKiW0cAx5kIvEw70MhQ/iSqrvtTNxO27PwvYoJdsPtmiXeoB+/CoejWp9dQqNvdAOK1rBhAJCsuf/EyMgVjnun/6FMG/oIaX/yX9RUoHN/VpFDlMU40jhggMoitkRtOVuAiWep4ah8hc756KlJTuzZB1yyO6D+vwqIyB6ZF8H2C1QapuIPT9JgrYkoHJoJVHFB14DbVXhmHGIwHorenH4SXZq6fZSnzBlA2c2kFcPQ
  template:
    metadata:
      creationTimestamp: null
      name: expedition-secret
      namespace: easybus-services
    type: Opaque
---
