apiVersion: v1
kind: Service
metadata:
  name: expedition-service
  namespace: easybus-services
spec:
  selector:
    app: expedition-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP