apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service
  namespace: easybus-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
    spec:
      containers:
      - name: member-service
        image: abdelilahxr/member-service:latest
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: member-config
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: member-secret
              key: DB_PASSWORD