apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: member-secret
  namespace: easybus-services
spec:
  encryptedData:
    DB_PASSWORD: AgB2935G4OwQmyEg3zIWvdDwW+WvcBpwG8X4+zKH5G/4NegvhVjnPbuBtshuFz7thaXLtKYfsNz6nwf1DGfVR1c6MocJzhCP3O5sNgsYHSSSEa1l8y4pD7dAVApXqUXBJkQltAZBjenReACpjrcP1p3ZCdgfqpYcrQ9oXY82RgcP3J7/kc3pOskb8M4i/E5dj+o7LPu/bBK5v2G1B3WI4vfMohqOPKzUl3NL4Zf9Zlv6S3ezuxfvFOyv6P9ltgEFFhk/tsZ6GchxL1jd6rjVUUQfONx+ig9QoOAGb/HelZARJUk3V7NDwsmehJoQU3S2Hhz6DKqlGh+KT38qytuOq6V5k1wEQvJAzEuwqI3qv+UrHxkem6pQqx/3oT5z9SnYj673UAIDbO150U+3iYsRxhrHoC7t42bEGCEt75gICRUxdQXLCPU1+YWEwgNg7UJ/RnUGnok2Hwo57iy9HlgfPoSDiuVs74R33twnqwz5hR9WEzuxbvQ5GMeSfWghYt+6Ufm7ygFhNxvr6e6WM7m6lGcRfmXpLp+Ppay3j0E60ymKSMzfZhPJy9Ikmul9mQle+RGemm4dB05GoXmroDZvahxcrROcNvRrVDK/po0x9zqPVlZBE9mjBIzND+IDfdyQtbsGc/SAMVYJFS5pN1wAqvpqYgL4ixEMRUhFwc5bJpVqxF54pQ0p9mKSmuu8Q9+rQne8WcrbWDA6
  template:
    metadata:
      creationTimestamp: null
      name: member-secret
      namespace: easybus-services
    type: Opaque
---
