apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-secret
  namespace: easybus-services
spec:
  encryptedData:
    DB_PASSWORD: AgDCLH/179viLCC48Qkhr0acQoNsIzRQ6ZZ9okyEvBDMdLmVBid9ndUOhmwJmW8+3mu9Ah2eAXNKGLUuN6xaaZ09G+hedR/aAsfxg4hvqlUfd6k8HVs72VT0ohTa4Ws0orhSg9ztepJJi8ETV1O6li0yAkDp9l5LLVsl5jRrgyDCUBwTZw6I+Puf9kPy7drlOXBr/AJXPI/K8LZ9FfrHtltXUeyOzTyjOlMXxIO2bDOM7QaB4wN37kEKkGQYAoHI1OnmigNdjhNYw7b09QsThAZ5Tf9RIi3LL4S+0T6omgAo54x7IMQ5/PC74niWiPfE5aGNddx/tjeHV2BcKk1amOgLxYF+eltSLjuV6vnF9wNb7VrpDfma6iJlhMqHRo/ZXkeMlyJnHeOr6oNGYZiAWUJOhAf/RrNrCE0amRoAqouMJpoDQefEg7g3WyH3yDpla8551rEgOnOh80arb3Riw+8J5cizh+K6MelRREWlDySfdJJtciVzaPAYs7KicsHuM4RN6O9h5kjFE5iGYxBi5o2v52Uz4PebVxloPIBMfbNQH+shyvRXimsaHhrnQFWVUbkJ/NrvRFJ40cnx3joO+dMDhVLFya4BzurCAwx0E0RTyr7MnPMdwMGa5v5MzcUKglNXgyFoaA4l1ngj86TgMNnyVG3KfVhWlrlFSU+XyJzR7l2husSA3ieZmk5wqnsTDeTkxDwcQZfO
  template:
    metadata:
      creationTimestamp: null
      name: payment-secret
      namespace: easybus-services
    type: Opaque
---
