apiVersion: v1
kind: Service
metadata:
  name: security-service
  namespace: easybus-services
spec:
  selector:
    app: security-service
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP