apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: security-secret
  namespace: easybus-services
spec:
  encryptedData:
    DB_PASSWORD: AgBq8kyfLNm3JGqJ/Z+ofHEh0TJBwiUvdM3LSiQKdt4c5aeK/z2yxFxgKDsqi6Tz9sfQXMaeP7WWRXAVSygvNSa7QikRcJPwy6kHvUuL7BBxWSx5zZhK9Ei7grOzxMI+X4ijs/UEsOi4tN1Ou2b8dIpPw9yiKjEs94lCRNk0LVdkYXflGj0G1e5WanJHORl+IIFR4MD5qrAAsBynxXc03up8t56frbtL3tHOmxEUkGNVyAjAogpIs7xvFTfa/UmhTe6Rka0VHWiGasVvv17OKDZbbXMHmXDjPNikNzim14jAOZNobkp2vsu0hFAl8RJH5xV76DOGt4+wIBAYQgr8HOHUcnvhPGQghiRmKtkZU6VzUoCRxi8fb+afxH5YbFi+9CyNWQ81UO1Y6dWw8wyBeJBOii3SIkGpxKp/8fYd3kRVJqgtQQ62nLWTLK4E2cWM/L76eiWtMHBHBZnSeCRBQGkiBLmg+kHRW93Pqz8o/2Th/+AbxTklmBElpzg5nnyPiC1VEurcpgDdonNqyTIUCHgaRZfuvQUi/lKC+ecP+LTICT0FLyigP8/HoTcy691XaMTPG67mCfeBUnzQA2HpY8W9mSvKxBsh/Fxp4FpiefJNwRcTvLBs6at6ECQslol8lrUcQiM4yEZ3QE/3cDEwDHpGcUPlXm8aFNxmq1wXMV/nk10sv16d97Qxl51dahI6IPYwUocvqGDc
  template:
    metadata:
      creationTimestamp: null
      name: security-secret
      namespace: easybus-services
    type: Opaque
---
